test:
  adapter: async

production:
  adapter: redis
  url: <%= ENV.fetch("REDIS_URL") { "redis://localhost:6379/1" } %>
  channel_prefix: shirtweb_production

development:
  adapter: redis
  url: redis://localhost:6379/1