default: &default
  host: 10.1.1.11
  adapter: postgresql
  encoding: unicode
  user: postgres
  pool: 10
  timeout: 5000
  password: p0stgr3s
development:
  <<: *default
  database: shirtweb_development
test:
  <<: *default
  database: shirtweb_test
sandbox:
  <<: *default
  host:  localhost
  database: shirtweb_sandbox
production:
  <<: *default
  host:  localhost
  database: shirtweb_production